import "bootstrap/dist/css/bootstrap.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";
import Navbar from "./components/navbar";
import ThemeRegistry from "./components/ThemeRegistry";
import Footer from "./components/footer";

export const dynamic = "force-dynamic";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{ minHeight: "100vh", display: "flex", flexDirection: "column"}}>
        <ThemeRegistry>
          <BootstrapClient />
          <Navbar />
          <div style={{flex: 1, display: "flex", flexDirection: "column"}}>
            {children}
          </div>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}

// https://www.kologojosias.com/tutorials/nextjs-kubernetes-econnrefused-build-time-fetch-solutions